name: HeroicRebuke
main: com.herocraftonline.squallseed31.heroicrebuke.HeroicRebuke
version: 0.2.5.82
commands:
  warn:
    description: Send a warning to misbehaving players that forces their acknowledgment.
    usage: /warn help - Displays usage instructions