name: HeroicRebuke
main: com.herocraftonline.squallseed31.heroicrebuke.HeroicRebuke
version: 1.2.5.85
commands:
  warn:
    description: Send a warning to misbehaving players that forces their acknowledgment.
    usage: /warn help - Displays usage instructions